{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bff-accounting.fullname" . }}
type: Opaque
stringData:
  EXPORT_SIGN_SECRET: "{{ .Values.env.EXPORT_SIGN_SECRET }}"
  DATABASE_URL: "{{ .Values.env.DATABASE_URL }}"
{{- end }}

