apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onprem-gateway.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "onprem-gateway.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "onprem-gateway.name" . }}
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "onprem-gateway.fullname" . }}
                  key: DATABASE_URL
            - name: EXPORT_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "onprem-gateway.fullname" . }}
                  key: EXPORT_SIGN_SECRET

