apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onprem-gateway.fullname" . }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  EXPORT_SIGN_SECRET: {{ .Values.secrets.EXPORT_SIGN_SECRET | quote }}

